include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o


ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo")
obj-y   +=  nt35590_hd720_dsi_cmd_auo.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_wvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_wvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"nt35590_hd720_dsi_cmd_auo_fwvga")
obj-y   +=  nt35590_hd720_dsi_cmd_auo_fwvga.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"LP079X01")
obj-y   +=  LP079X01.o
endif
