include $(srctree)/drivers/misc/mediatek/Makefile.custom


obj-y   +=  mtk_tpd.o
obj-y   +=  tpd_button.o
obj-y   +=  tpd_calibrate.o
obj-y   +=  tpd_debug.o
obj-y   +=  tpd_default.o
obj-y   +=  tpd_init.o
obj-y   +=  tpd_misc.o
obj-y   +=  tpd_setting.o
obj-$(CONFIG_TOUCHSCREEN_FT5606) +=  ft5606/
obj-$(CONFIG_TOUCHSCREEN_GT9xx) +=  GT9xx/
