include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/ili2139/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ili2139/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  iLitek.o

