/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6574. Copyright MediaTek Inc. (C) 2013.
 * Tue Feb 03 15:59:44 2015
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>
void pmu_drv_tool_customization_init(void)
{
}


